CREATE TABLE `yinuojr_ops.opr_cert_reissue_info` (
  `ID` bigint(32) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `apply_no` varchar(36) NOT NULL COMMENT '申请编号',
  `operator_id` bigint(32) NOT NULL COMMENT '所属运营方',
  `operator_name` varchar(64) NOT NULL COMMENT '企业名称',
  `create_company_id` bigint(32) DEFAULT NULL COMMENT '创建申请企业ID',
  `create_company_name` varchar(64) DEFAULT NULL COMMENT '创建申请企业NAME',
  `company_id` bigint(32) DEFAULT NULL COMMENT '企业ID',
  `company_name` varchar(64) DEFAULT NULL COMMENT '企业名称',
  `social_credit_code` varchar(18) DEFAULT NULL COMMENT '统一社会信用代码',
  `cert_apply_type` tinyint(2) DEFAULT NULL COMMENT '1、U盾证书  2、印章服务软证书',
  `cert_deadline` datetime DEFAULT NULL COMMENT '申请证书到期日',
  `cert_dn_no` varchar(128) DEFAULT NULL COMMENT '证书的DN码',
  `reference_code` varchar(128) DEFAULT NULL COMMENT '参考吗',
  `authorization_code` varchar(128) DEFAULT NULL COMMENT '授权码',
  `cert_bind_user` varchar(64) DEFAULT NULL COMMENT '绑定用户名',
  `cert_status` tinyint(2) DEFAULT NULL COMMENT '证书申请状态',
  `total_price` bigint(20) DEFAULT NULL COMMENT '证书总价',
  `apply_time` datetime DEFAULT NULL COMMENT '提交工单时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint(2) DEFAULT NULL COMMENT '0、未删除  1、已删除',
  `apply_step` tinyint(2) DEFAULT NULL COMMENT '申请步骤',
  `address_id` bigint(32) DEFAULT NULL COMMENT '地址Id',
  `address` varchar(200) DEFAULT NULL COMMENT '收件地址',
  `addressee` varchar(50) DEFAULT NULL COMMENT '收件人',
  `mobile` varchar(11) DEFAULT NULL COMMENT '手机号',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='证书补办信息表';

CREATE TABLE `yinuojr_ops.opr_cert_replace_info` (
  `ID` bigint(32) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `apply_no` varchar(36) DEFAULT NULL COMMENT '申请编号',
  `operator_id` bigint(32) DEFAULT NULL COMMENT '所属运营方',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '企业名称',
  `create_company_id` bigint(32) DEFAULT NULL COMMENT '创建申请企业ID',
  `create_company_name` varchar(64) DEFAULT NULL COMMENT '创建申请企业NAME',
  `company_id` bigint(32) DEFAULT NULL COMMENT '企业ID',
  `company_name` varchar(64) DEFAULT NULL COMMENT '企业名称',
  `social_credit_code` varchar(18) DEFAULT NULL COMMENT '统一社会信用代码',
  `cert_apply_type` tinyint(2) DEFAULT NULL COMMENT '1、U盾证书  2、印章服务软证书',
  `old_cert_deadline` datetime DEFAULT NULL COMMENT '申请证书到期日',
  `old_cert_dn_no` varchar(128) DEFAULT NULL COMMENT '证书的DN码',
  `old_reference_code` varchar(128) DEFAULT NULL COMMENT '参考吗',
  `old_authorization_code` varchar(128) DEFAULT NULL COMMENT '授权码',
  `new_cert_deadline` datetime DEFAULT NULL COMMENT '申请证书到期日',
  `new_cert_dn_no` varchar(128) DEFAULT NULL COMMENT '证书的DN码',
  `new_reference_code` varchar(128) DEFAULT NULL COMMENT '参考吗',
  `new_authorization_code` varchar(128) DEFAULT NULL COMMENT '授权码',
  `cert_bind_user` varchar(64) DEFAULT NULL COMMENT '绑定用户名',
  `cert_status` tinyint(2) DEFAULT NULL COMMENT '证书申请状态',
  `apply_time` datetime DEFAULT NULL COMMENT '提交工单时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint(2) DEFAULT NULL COMMENT '0、未删除  1、已删除',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=432 DEFAULT CHARSET=utf8 COMMENT='证书替换信息表';


CREATE TABLE `yinuojr_ops.opr_cert_reset_pin_info` (
  `ID` bigint(32) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `apply_no` varchar(36) DEFAULT NULL COMMENT '申请编号',
  `operator_id` bigint(32) DEFAULT NULL COMMENT '所属运营方',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '企业名称',
  `create_company_id` bigint(32) DEFAULT NULL COMMENT '创建申请企业ID',
  `create_company_name` varchar(64) DEFAULT NULL COMMENT '创建申请企业NAME',
  `company_id` bigint(32) DEFAULT NULL COMMENT '企业ID',
  `company_name` varchar(64) DEFAULT NULL COMMENT '企业名称',
  `social_credit_code` varchar(18) DEFAULT NULL COMMENT '统一社会信用代码',
  `cert_apply_type` tinyint(2) DEFAULT NULL COMMENT '1、U盾证书  2、印章服务软证书',
  `cert_deadline` datetime DEFAULT NULL COMMENT '申请证书到期日',
  `cert_dn_no` varchar(128) DEFAULT NULL COMMENT '证书的DN码',
  `reference_code` varchar(128) DEFAULT NULL COMMENT '参考吗',
  `authorization_code` varchar(128) DEFAULT NULL COMMENT '授权码',
  `cert_bind_user` varchar(64) DEFAULT NULL COMMENT '绑定用户名',
  `address_id` bigint(32) DEFAULT NULL COMMENT '地址Id',
  `address` varchar(200) DEFAULT NULL COMMENT '收件地址',
  `mobile` varchar(11) DEFAULT NULL COMMENT '手机号',
  `addressee` varchar(50) DEFAULT NULL COMMENT '收件人',
  `cert_status` tinyint(2) DEFAULT NULL COMMENT '证书申请状态',
  `apply_time` datetime DEFAULT NULL COMMENT '提交工单时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `is_deleted` tinyint(2) DEFAULT NULL COMMENT '0、未删除  1、已删除',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=432 DEFAULT CHARSET=utf8 COMMENT='证书重置信息表';